### PR TITLE
Update v0.8.2

### PR DESCRIPTION
**Pull request by rxm7706**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by rxm7706** [comment]
@conda-forge-admin, please rerender

**Comment by rxm7706** [comment]
@jakirkham @Anthchirp 
This is ready to review - and is a dependency for 
  - https://github.com/conda-forge/pylint-django-feedstock/pull/42
Could you please review and merge. 
Thank you and Regards.

**Comment by rxm7706** [comment]
> @jakirkham @Anthchirp
> This is ready to review - and is a dependency for

> @jakirkham @Anthchirp could you please review when you get a chance.

**Comment by Anthchirp** [comment]
@conda-forge-admin, please rerender

**Review by Anthchirp — APPROVED** [review]
LGTM. Would you like to take over package maintenance? If so, submit a PR replacing my name with yours in the recipe file, and nag me until I merge it :slightly_smiling_face:

**Comment by rxm7706** [comment]
> LGTM. Would you like to take over package maintenance? If so, submit a PR replacing my name with yours in the recipe file, and nag me until I merge it 🙂

@Anthchirp happy to help
- https://github.com/conda-forge/pylint-plugin-utils-feedstock/pull/17

**Pull request merged**
